# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo asdf
  displayName: 'asdf'

- script: The pipeline ran at $(date) > testfile.txt
  displayName: 'Put date in file.'
  
  
- publish: $(System.DefaultWorkingDirectory)/testfile.txt
  artifact: testdir

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
